export interface Operaciones{
    idOperaciones:number;
    dniProfesional:number;
    apellidoProfesional:string;
    nombreProfesional:string;
    mailProfesional:string;
    fechaTransaccion:string;
    fechaPago:string;
    dniCliente:string;
    apellidoCliente:string;
    nombreCliente:string;
    telefonoCliente:string;
    mailCliente:string;
    tarjeta:string;
    importeVenta:number;
    importeCobrar:number;
    cuotas:number;
    importeCarga:number;
    importeCuota:number;
    codigoAuto:string;
    cupon:number;
}